version: '3.4'

services:
  MongoDB:
      image: mongo
      build:
        context: .
        dockerfile: ./MongoDockerfile
      container_name: MongoDB_Container
      ports: 
        - 27017:27017
      expose:
        - 27017

  pythonApp:
    image: python
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: Flask_Container
  
    ports:
      - 80:80