apiVersion: v1
kind: Service
metadata:
    name: sainathzesstasomeoneswebapptask
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: sainathzesstasomeoneswebapptask